### ISSUE TITLE
请问一下，有完整的项目备份嘛？

### ISSUE THREAD

**Issue by Volundio** [MaxSecurity/BiliExper#1]
想求一个完整未修改的项目，感谢

**Comment by MaxSecurity** [comment]
我就修改了main文件只需要注释掉
while True: #死循环 每一个小时运行一次配置
    main(**kwargs)
    time.sleep(3600)
这段代码改成
main(**kwargs)这个就行了

**Comment by Volundio** [comment]
> 我就修改了main文件只需要注释掉
> while True: #死循环 每一个小时运行一次配置
> main(**kwargs)
> time.sleep(3600)
> 这段代码改成
> main(**kwargs)这个就行了

原来如此，感谢

**Comment by MaxSecurity** [comment]
> > 我就修改了main文件只需要注释掉
> > 而True：＃死循环每一小时运行一次配置
> > main（** kwargs）
> > time.sleep 
> > （3600）此代码改成
> > main（** kwargs）这个就行了
> 
> 原来如此，感谢

OK
