### ISSUE TITLE
风纪委投票的bug分析

### ISSUE THREAD

**Issue by zhongfly** [MaxSecurity/BiliExper#10]
近来发现风纪委投票频繁出现弃权，怀疑是bug，查阅相关api做以下分析：
https://github.com/MaxSecurity/BiliExper/blob/master/tasks/judgement_task.py#L81 中vode应该是笔误，实际应该是vote
APi文档：https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/blackroom/jury/action.md#%E8%BF%9B%E8%A1%8C%E4%BB%B2%E8%A3%81%E6%8A%95%E7%A5%A8

**Comment by zhongfly** [comment]
但感觉问题不是在这个地方，看日志中的相关提示是：
```
获取风纪委员案件他人投票结果异常，原因为无法访问未匹配案件，使用默认投票参数

风纪委员投票id为1849943的案件失败，信息为：请勿重复投票
```

**Comment by zhongfly** [comment]
继续排查
同样是使用默认参数，这次成功了：
```
获取风纪委员案件id为1893677他人投票结果异常，原因为无法访问未匹配案件，使用默认投票参数，投(删除)票

风纪委员成功为id为1893677的案件投(删除)票
```
这次导致投出的弃权票：
```
获取风纪委员案件id为1896627他人投票结果异常，原因为无法访问未匹配案件，使用默认投票参数，投(删除)票

风纪委员投票id为1896627的案件失败，信息为：请勿重复投票
```

```
获取风纪委员案件1895832他人投票结果异常，原因为无法访问未匹配案件，使用默认投票参数

asyncBiliApi:为案件1895832投票，参数为：{'vote': 4, 'attr': 0}

尝试为id为1895832的案件投(删除)票

风纪委员投票id为1895832的案件失败，信息为：请勿重复投票，投票参数为OrderedDict([('vote', 4), ('attr', 0)])
```
问题可能是是出在使用默认参数投票的请求，默认参数应该是没有问题的，但为什么会是重复投票——弃权呢？
@MaxSecurity

**Comment by zhongfly** [comment]
还是没搞清楚，目前感觉应该是卡在投票中（即程序投票未成功），超时后就变成弃权了

**Comment by MaxSecurity** [comment]
> 还是没搞清楚，现在觉得应该是卡在投票中了（即投票程序未成功），以后就可以弃权了

目前我还没遇到这种情况估计我没有注意日志周末我看看

**Comment by zhongfly** [comment]
> > 还是没搞清楚，现在觉得应该是卡在投票中了（即投票程序未成功），以后就可以弃权了
> 
> 目前我还没遇到这种情况估计我没有注意日志周末我看看

时不时就有这种情况，很奇怪，你可以看看https://www.bilibili.com/judgement/index 投票记录
![Screenshot_20210809222853](https://user-images.githubusercontent.com/11155705/128723138-d3c2c7bd-cdf1-4211-9fa5-9ca327f58906.png)

**Comment by MaxSecurity** [comment]
> > > 还是没搞清楚，现在觉得应该是卡在投票中了（即投票程序未成功），以后就可以弃权了
> > 
> > 
> > 目前我还没遇到这种情况估计我没有注意日志周末我看看
> 
> 时不时就有这种情况，很奇怪，你可以看看https://www.bilibili.com/judgement/index 投票记录
> ![Screenshot_20210809222853](https://user-images.githubusercontent.com/11155705/128723138-d3c2c7bd-cdf1-4211-9fa5-9ca327f58906.png)

我查看了一下进两个月就出现了一次弃权。。。玄学问题。。

**Comment by zhongfly** [comment]
> 我查看了一下进两个月就出现了一次弃权。。。玄学问题。。

我一般出现时，那个时段的投票就全弃权了…我目前先自己在获取案件/获取他人投票情况/投票之间添加一些等待时间试试

**Comment by zhongfly** [comment]
这段时间，风纪委任务里每个请求都等待数秒，出现弃权的现象明显减少，但依然会出现。

**Comment by MaxSecurity** [comment]
> 这段时间，风纪委任务里每个请求都等待数秒，出现弃权的现象明显减少，但依然会出现。

我没有遇到这种情况 感觉是网络波动问题
