### ISSUE TITLE
云函数

### ISSUE THREAD

**Issue by YYplus** [MaxSecurity/BiliExper#2]
部署到云函数的教程不能用了吗，没有run BiliExp了

**Comment by MaxSecurity** [comment]
> 部署到云函数的教程不能用，没有运行 BiliExp了

此项目不支持Actions服务了会被封项目的

**Comment by MaxSecurity** [comment]
> 部署到云函数的教程不能用了吗，没有run BiliExp了

**Comment by zhongfly** [comment]
写了一个教程https://github.com/MaxSecurity/BiliExper/issues/3

**Comment by YYplus** [comment]
> 写了一个教程#3

谢谢
