### ISSUE TITLE
代码兼容性问题

### ISSUE THREAD

**Issue by zhongfly** [MaxSecurity/BiliExper#20]
https://github.com/MaxSecurity/BiliExper/commit/b7c3a9acaa4ff88361e8551ff61161a6a7af672a @acooler15 的修改引入了python3.7的新方法datetime.time.fromisoformat，使得python3.6不再兼容
由于腾讯云函数的python环境只有3.6版本，为了使得能正常运行，项目应该兼容3.6

另外https://github.com/MaxSecurity/BiliExper/blob/master/BiliExp.py#L250 是缩进错误吧？

**Comment by zhongfly** [comment]
增加一个函数来解析即可：
```python
def fromisoformat(time_str)
    return datetime.datetime.strptime(time_str,'%H:%M:%S').time()
```

**Comment by acooler15** [comment]
> [b7c3a9a](https://github.com/MaxSecurity/BiliExper/commit/b7c3a9acaa4ff88361e8551ff61161a6a7af672a) @acooler15 的修改引入了python3.7的新方法datetime.time.fromisoformat，使得python3.6不再兼容
> 由于腾讯云函数的python环境只有3.6版本，为了使得能正常运行，项目应该兼容3.6
> 
> 另外https://github.com/MaxSecurity/BiliExper/blob/master/BiliExp.py#L250 是缩进错误吧？

![Suggestion](https://user-images.githubusercontent.com/19186382/128327786-256a1dce-b1c5-4566-b6fe-3599fb864731.gif)
查python文档时没注意兼容性的问题😂
