### ISSUE TITLE
docker运行出现读取配置异常

### ISSUE THREAD

**Issue by FairyWorld** [MaxSecurity/BiliExper#26]
![image](https://user-images.githubusercontent.com/32956212/128609719-a8bc8b99-d27a-432e-a29b-4225ebb51ba5.png)

**Comment by FairyWorld** [comment]
好像前两周的docker是正常的, 今天重新打包后就有问题了

**Comment by FairyWorld** [comment]
![image](https://user-images.githubusercontent.com/32956212/128639122-628ce557-db2a-4b64-ba33-61b181e0aeff.png)
args.get("configfile",None)好像是这里有问题

**Comment by zhongfly** [comment]
有毒啊，腾讯云里python是3.6.1，args是dict，而我本地的3.6.8里是Namesapce，估计你们docker也是这样。
获取不存在的key时：
前者如果直接用args.XXX时直接报错，后者（Namesapce）返回None
前者可以args.get来获取时，可以设置不存在时返回None，后者没有get方法
我再改一下吧

为了兼容性，要不统一成3.6.1吧……

**Comment by FairyWorld** [comment]
![image](https://user-images.githubusercontent.com/32956212/128709190-cf162c17-b094-4495-9d9b-f84a041cdd69.png)
大佬可以教下Docker/entrypoint.sh的这几个参数怎么传进去吗? 这个daemon和cron参数是不是用来定时更新下载最新仓库代码的?

**Comment by zhongfly** [comment]
> ![image](https://user-images.githubusercontent.com/32956212/128709190-cf162c17-b094-4495-9d9b-f84a041cdd69.png)
> 大佬可以教下Docker/entrypoint.sh的这几个参数怎么传进去吗? 这个daemon和cron参数是不是用来定时更新下载最新仓库代码的?

我不用docker的…你找找文档看看

**Comment by if1y** [comment]
除了 `only_download`，都是原有的参数 https://github.com/MaxSecurity/BiliExper#%E6%96%B9%E5%BC%8F%E5%85%ADdocker%E5%AE%89%E8%A3%85

`daemon` 是进程守护
`cron` 是定时执行表达式
