### ISSUE TITLE
安装模块失败 

### ISSUE THREAD

**Issue by Tang121337** [MaxSecurity/BiliExper#29]
安装模块失败  一直卡在这怎么办啊 py版本3.9.6 -win10

**Comment by Tang121337** [comment]
ERROR: Command errored out with exit status 1:
     command: 'h:\python\python3.9.6\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tom\\AppData\\Local\\Temp\\pip-install-no95sjob\\uvloop_884d59c86fc54f58be8383d2b5fc2b53\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tom\\AppData\\Local\\Temp\\pip-install-no95sjob\\uvloop_884d59c86fc54f58be8383d2b5fc2b53\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Tom\AppData\Local\Temp\pip-pip-egg-info-oo_1mtv9'
         cwd: C:\Users\Tom\AppData\Local\Temp\pip-install-no95sjob\uvloop_884d59c86fc54f58be8383d2b5fc2b53\
    Complete output (10 lines):

    -------------------------------------------------------------------------------
    <string> 1 <module>


    setup.py 15 <module>
    raise RuntimeError('uvloop does not support Windows at the moment')

    RuntimeError:
    uvloop does not support Windows at the moment
    ----------------------------------------
WARNING: Discarding http://mirrors.aliyun.com/pypi/packages/84/2e/462e7a25b787d2b40cf6c9864a9e702f358349fc9cfb77e83c38acb73048/uvloop-0.14.0.tar.gz#sha256=123ac9c0c7dd71464f58f1b4ee0bbd81285d96cdda8bc3519281b8973e3a461e (from http://mirrors.aliyun.com/pypi/simple/uvloop/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement uvloop==0.14.0 (from versions: 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.15, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.23, 0.4.24, 0.4.25, 0.4.26, 0.4.27, 0.4.28, 0.4.29, 0.4.30, 0.4.31, 0.4.32, 0.4.33, 0.4.34, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.6.0, 0.6.5, 0.6.6, 0.6.7, 0.6.8, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0rc1, 0.12.0, 0.12.1, 0.12.2, 0.13.0rc1, 0.13.0, 0.14.0rc1, 0.14.0rc2, 0.14.0, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.16.0)
ERROR: No matching distribution found for uvloop==0.14.0

**Comment by Tang121337** [comment]
![111](https://user-images.githubusercontent.com/30113090/130347287-20976f71-a3bb-4fac-a5f8-aa3a86c176b8.png)
他是不支持wiwindows吗。

**Comment by MaxSecurity** [comment]
支持的 你直接 pip3 install uvloop 安装

**Comment by Tang121337** [comment]
> 支持的你直接pip3 install uvloop 安装
![image](https://user-images.githubusercontent.com/30113090/130381880-e237de75-3811-40da-81b2-7cf7c911f147.png)
我试过。他直接报错 pip已经升级到最新了  百度了很久没找到解决方法

**Comment by MaxSecurity** [comment]
> uvloop

稍等我去看一下

> > 支持的你直接pip3 install uvloop 安装
> > ![image](https://user-images.githubusercontent.com/30113090/130381880-e237de75-3811-40da-81b2-7cf7c911f147.png)
> > 我试过。他直接报错 pip已经升级到最新了  百度了很久没找到解决方法

稍等我去看一下这个组件是否必备

**Comment by MaxSecurity** [comment]
> > 支持的你直接pip3 install uvloop 安装
> > ![image](https://user-images.githubusercontent.com/30113090/130381880-e237de75-3811-40da-81b2-7cf7c911f147.png)
> > 我试过。他直接报错 pip已经升级到最新了  百度了很久没找到解决方法

尝试一下
```
easy_install pip3
```
```
pip3 install uvloop
```

实在不行去官网下载手动安装把https://pypi.org/project/uvloop/#files

**Comment by Tang121337** [comment]
官网下载手动安装哪个是windows版本的。我看好像没有
![image](https://user-images.githubusercontent.com/30113090/130454315-0a852731-313a-416d-8d39-7fb9c4006d59.png)
上面两个指令
![image](https://user-images.githubusercontent.com/30113090/130454484-a4c87538-6fc7-408d-8df0-8ebac48dc6c8.png)

**Comment by Tang121337** [comment]
一键安装库就报错这个
![image](https://user-images.githubusercontent.com/30113090/130454904-fd2755a3-b7b7-487a-8e3f-37f29d56be63.png)
大哥看看什么问题

**Comment by Tang121337** [comment]
raise RuntimeError('uvloop does not support Windows at the moment')

**Comment by Tang121337** [comment]
他告诉我不支持Windows

**Comment by MaxSecurity** [comment]
> 他告诉我不支持Windows

不应该啊我 win上面运行没毛病啊
![image](https://user-images.githubusercontent.com/16812469/130543513-348e520c-f0d5-4f34-af34-0268328f0adc.png)

**Comment by Tang121337** [comment]
我去换py3.8试试 我去百度搜的都是这库不支持windows

**Comment by Tang121337** [comment]
能不能整合打包一个

**Comment by Tang121337** [comment]
![O4 %F8) P$WX9(3K(68BYDA](https://user-images.githubusercontent.com/30113090/130548047-9e9845db-3f88-4115-9d38-c4cbea18d8d0.png)

**Comment by Tang121337** [comment]
![image](https://user-images.githubusercontent.com/30113090/130552378-5fc5c60e-09f4-4f4b-a5f7-9398b7f742a5.png)
3.8同样的报错 麻了

**Comment by MaxSecurity** [comment]
> ![形象](https://user-images.githubusercontent.com/30113090/130552378-5fc5c60e-09f4-4f4b-a5f7-9398b7f742a5.png)
> 3.8同样的报错麻了

直接运行程序看看程序能否运行

**Comment by Tang121337** [comment]
> > ![形象](https://user-images.githubusercontent.com/30113090/130552378-5fc5c60e-09f4-4f4b-a5f7-9398b7f742a5.png)
> > 3.8同样的报错麻了
> 
> 直接运行程序看看能不能运行

不能运行 作者你是3.8环境的吗 我这uvloop无论怎么装都装不上

**Comment by MaxSecurity** [comment]
> > > ![形象](https://user-images.githubusercontent.com/30113090/130552378-5fc5c60e-09f4-4f4b-a5f7-9398b7f742a5.png)
> > > 3.8同样的报错麻了
> > 
> > 
> > 直接运行程序看看能不能运行
> 
> 不能运行 作者你是3.8环境的吗 我这uvloop无论怎么装都装不上

换个环境的吧建议Ubuntu系统
