### ISSUE TITLE
报错：原因为ssl should be SSLContext, bool, Fingerprint or None, got False instead

### ISSUE THREAD

**Issue by 1520287102** [MaxSecurity/BiliExper#30]
![image](https://user-images.githubusercontent.com/47970841/130729325-cad296bd-9074-456f-8c5c-298e9fd122ae.png)
求大佬解释一下

**Comment by MaxSecurity** [comment]
你使用是py几点几

**Comment by 1520287102** [comment]
> 你用的是皮书几

3.9

**Comment by 1520287102** [comment]
必须要用3.8 ？

**Comment by MaxSecurity** [comment]
> 必须要用3.8 ？

好像是的 3.9有转化问题目前没时间看 你可以换到3.8先用着有时间看一下
