### ISSUE TITLE
粉丝勋章的读取被限制了(已解决)，能限制一下发弹幕的速度吗

### ISSUE THREAD

**Issue by Gensokyo1995** [MaxSecurity/BiliExper#35]
[2021-09-30 05:34:16,143] [WARNING]: 获取有勋章的直播间失败，信息为pageSize最多10个

还有直播间发一条弹幕点亮牌子获取经验能限制一下发弹幕的速度吗，最好2-3秒才发一次，不然会发送失败，会提示发送弹幕速度过快

**Comment by Gensokyo1995** [comment]
将xlive_heartbeat_task.py中的ret = await biliapi.xliveFansMedal(page, 50)改成ret = await biliapi.xliveFansMedal(page, 10)就可以正常使用了，希望有人能改下发送弹幕的速度

**Comment by MaxSecurity** [comment]
ok 马上更新

**Comment by MaxSecurity** [comment]
已经更新完毕
