### ISSUE TITLE
关于腾讯云函数部署

### ISSUE THREAD

**Issue by ez452** [MaxSecurity/BiliExper#39]
2.2 添加完上面 2个"Secrets"后，进入"Actions"(上面那个不是Secrets下面那个) --》"deploy for serverless"，点击右边的"Run workflow"即可部署至腾讯云函数(如果出错请在红叉右边点击"deploy for serverless"查看部署任务的输出信息找出错误原因)
2.2.1 首次fork可能要去actions里面同意使用actions条款，如果"Actions"里面没有"deploy for serverless"，点一下右上角的"star"，"deploy for serverless"就会出现在"Actions"里面

为什么我找不到"deploy for serverless"，求助大佬，找了n久了。按着2.2.1做了，也没有。

**Comment by MaxSecurity** [comment]
不好意思 我没用过云函数部署我直接使用服务器运行的

**Comment by zhongfly** [comment]
![image](https://user-images.githubusercontent.com/11155705/137892602-bf207779-5b3a-4327-a99c-70ccbe678443.png)

Readme开头就写了，为避免滥用已删除action相关文件，本项目不含任何action。希望你能认真看一下，就在开头，这么大的字
请自己手动部署到腾讯云函数

@MaxSecurity 建议写得更白话一点：

> 原项目由于Actions导致项目被封，所以此备份仓库**不包含任何Actions**，**无法使用**原教程中的所有涉及action的操作/功能。

另外：
“此项目只是备份和自己修改还有其他小伙伴Pull，不存在**_Actione_**服务”打错了

**Comment by ez452** [comment]
我就是手动下的包，但是教程有这一步，我不能用才过来问的，我昨天看了800遍了，早看到了，倒是你，没好好看教程文件就过来说教我了，你怕不是连我问得问题都没看吧，瞎BB啥呢，笑死了

**Comment by ez452** [comment]
> ![image](https://user-images.githubusercontent.com/11155705/137892602-bf207779-5b3a-4327-a99c-70ccbe678443.png)
> 
> Readme开头就写了，为避免滥用已删除action相关文件，本项目不含任何action。希望你能认真看一下，就在开头，这么大的字 请自己手动部署到腾讯云函数
> 
> @MaxSecurity 建议写得更白话一点：
> 
> > 原项目由于Actions导致项目被封，所以此备份仓库**不包含任何Actions**，**无法使用**原教程中的所有涉及action的操作/功能。
> 
> 另外： “此项目只是备份和自己修改还有其他小伙伴Pull，不存在**_Actione_**服务”打错了

**Comment by zhongfly** [comment]
> ez452 <notifications@github.com> 于2021年10月20日周三 下午3:08写道：
> 我就是手动下的包，但是教程有这一步，我不能用才过来问的，我昨天看了800遍了，早看到了，倒是你，没好好看教程文件就过来说教我了，你怕不是连我问得问题都没看吧，瞎BB啥呢，笑死了

![image](https://user-images.githubusercontent.com/11155705/138046406-f3c37ff3-c9e4-4c63-985a-8b0186348944.png)
