### ISSUE TITLE
lottery_task 疑似失效

### ISSUE THREAD

**Issue by gitiray** [MaxSecurity/BiliExper#4]
请问您是否有使用动态转发抽奖（lottery_task）功能。
我最近几天出现转发失败，怀疑是官方接口调整了，特此求证。

**Comment by MaxSecurity** [comment]
> 因为你是否有使用动态转发抽（彩票任务）功能。
> 我最近几天出现评论失败，这是官方接口调整了，特求证。

的确失效了，有空更新一下吧或者大佬自行修改pull一下也可以

**Comment by MaxSecurity** [comment]
> 请问您是否有使用动态转发抽奖（lottery_task）功能。
> 我最近几天出现转发失败，怀疑是官方接口调整了，特此求证。

不对不对还是正常转发抽奖的我刚刚查看十分钟前还是转发了抽奖的
