### ISSUE TITLE
大哥，请教个问题，我这错误是因为安装requirements.txt没装好么

### ISSUE THREAD

**Issue by dbwuac** [MaxSecurity/BiliExper#5]
![QQ截图20210604234555](https://user-images.githubusercontent.com/77618659/120828544-3bd8ef00-c58f-11eb-908f-77d46b45b9d7.png)

**Comment by MaxSecurity** [comment]
对 你再运行目录执行这串命令` pip3 install -r requirements.txt`或者` pip install -r requirements.txt`

**Comment by dbwuac** [comment]
谢谢，懂得了
