### ISSUE TITLE
目前已知失效的API

### ISSUE THREAD

**Issue by gitiray** [MaxSecurity/BiliExper#9]
1. 小心心 Heartbeat
2. 银瓜子
3. 礼物赠送

**Comment by jsyzdej** [comment]
Heartbeat倒不如说是缺少s和visit_id参数，补上这两个就OK了

**Comment by gitiray** [comment]
> 
> 
> Heartbeat倒不如说是缺少s和visit_id参数，补上这两个就OK了

大佬有改好的成品吗，或许可以来个 pr

**Comment by jsyzdej** [comment]
> 
> 
> > Heartbeat倒不如说是缺少s和visit_id参数，补上这两个就OK了
> 
> 大佬有改好的成品吗，或许可以来个 pr

你可以参考下面这个方案改
https://mudew.com/20200722/bilibili-webside-live-broadcast-encryption-heartbeat-request-analysis/

**Comment by gitiray** [comment]
> 
> 
> > > Heartbeat倒不如说是缺少s和visit_id参数，补上这两个就OK了
> > 
> > 
> > 大佬有改好的成品吗，或许可以来个 pr
> 
> 你可以参考下面这个方案改
> https://mudew.com/20200722/bilibili-webside-live-broadcast-encryption-heartbeat-request-analysis/

我看过了，解密本来就有，visit_id 是空值应该可以忽略

**Comment by acooler15** [comment]
应援团签到也失效了，

> > > > Heartbeat倒不如说是缺少s和visit_id参数，补上这两个就OK了
> > > 
> > > 
> > > 大佬有改好的成品吗，或许可以来个 pr
> > 
> > 
> > 你可以参考下面这个方案改
> > https://mudew.com/20200722/bilibili-webside-live-broadcast-encryption-heartbeat-request-analysis/
> 
> 我看过了，解密本来就有，visit_id 是空值应该可以忽略

好像是那个加密服务器废了。。。

**Comment by if1y** [comment]
> 应援团签到也失效了，
> 
> > > > > Heartbeat倒不如说是缺少s和visit_id参数，补上这两个就OK了
> > > > 
> > > > 
> > > > 大佬有改好的成品吗，或许可以来个 pr
> > > 
> > > 
> > > 你可以参考下面这个方案改
> > > https://mudew.com/20200722/bilibili-webside-live-broadcast-encryption-heartbeat-request-analysis/
> > 
> > 
> > 我看过了，解密本来就有，visit_id 是空值应该可以忽略
> 
> 好像是那个加密服务器废了。。。

我加了本地解密模块也不行
